

-- test data
INSERT INTO ANALYSIS (ID, APPLICATION, MODULE, EXECDATE, RESULT) VALUES (1, 'CRS', 'ADEP20170204', now(), 'RECHAZADO');
INSERT INTO ANALYSIS (ID, APPLICATION, MODULE, EXECDATE, RESULT) VALUES (2, 'CRS', 'ART20161050', now(), 'APROBADO');
INSERT INTO ANALYSIS (ID, APPLICATION, MODULE, EXECDATE, RESULT) VALUES (3, 'SSDD', 'DEV1.3', now(), 'RECHAZADO');
